# Question
Look at this function:

```js
const bailOut = () => {
  for (let i = 0; i < 5; i++) {
    if (i > 3) return;
    console.log('Inside the loop', i);
  }
  console.log('Outside the loop');
};
```

Is that `console.log('Outside the loop');` ever going to run? Why or why not?

# Answer
The `console.log('Outside the loop');` will never run. Once the condition `i > 3` is met, the `return` keyword terminates the function and no code after the function is read. 

# Teacher Feedback
